export const SET_UNSUBSCRIBE_NEWS_LETTER = 'SET_UNSUBSCRIBE_NEWS_LETTER';
export const SET_UNSUBSCRIBE_NEWS_LETTER_SUCCESS =
  'SET_UNSUBSCRIBE_NEWS_LETTER_SUCCESS';
export const SET_UNSUBSCRIBE_NEWS_LETTER_FAILED =
  'SET_UNSUBSCRIBE_NEWS_LETTER_FAILED';
