export const LIFETAG_RESPONSE_STATE = {
  LIFE_TAG_NOT_FOUND: 'LIFE_TAG_NOT_FOUND',
  LIFE_TAG_NOT_LINKED: 'LIFE_TAG_NOT_LINKED',
};
// LIFETAG INITIAL STATE
export const SET_LIFETAG_TEMP_STATE = 'SET_LIFETAG_TEMP_STATE';
export const SET_LIFETAG_TEMP_STATE_CLEAR = 'SET_LIFETAG_TEMP_STATE_CLEAR';
export const SET_LIFETAG_TEMP_ORDER_STATE = 'SET_LIFETAG_TEMP_ORDER_STATE';
export const SET_LIFETAG_TEMP_ORDER_STATE_CLEAR =
  'SET_LIFETAG_TEMP_ORDER_STATE_CLEAR';

// LIFETAG PRODUCT DETAIL
export const GET_LIFETAG_PRODUCT_DETAIL = 'GET_LIFETAG_PRODUCT_DETAIL';
export const GET_LIFETAG_PRODUCT_DETAIL_SUCCESS =
  'GET_LIFETAG_PRODUCT_DETAIL_SUCCESS';
export const GET_LIFETAG_PRODUCT_DETAIL_FAILED =
  'GET_LIFETAG_PRODUCT_DETAIL_FAILED';
export const GET_LIFETAG_PRODUCT_DETAIL_CLEAR =
  'GET_LIFETAG_PRODUCT_DETAIL_CLEAR';

// LIFETAG PROFILE PUBLIC
export const GET_LIFETAG_PROFILE = 'GET_LIFETAG_PROFILE';
export const GET_LIFETAG_PROFILE_SUCCESS = 'GET_LIFETAG_PROFILE_SUCCESS';
export const GET_LIFETAG_PROFILE_FAILED = 'GET_LIFETAG_PROFILE_FAILED';
export const GET_LIFETAG_PROFILE_CLEAR = 'GET_LIFETAG_PROFILE_CLEAR';

// LIFETAG PROFILE PUBLIC
export const GET_LIFETAG_PROFILE_PUBLIC = 'GET_LIFETAG_PROFILE_PUBLIC';
export const GET_LIFETAG_PROFILE_PUBLIC_SUCCESS =
  'GET_LIFETAG_PROFILE_PUBLIC_SUCCESS';
export const GET_LIFETAG_PROFILE_PUBLIC_FAILED =
  'GET_LIFETAG_PROFILE_PUBLIC_FAILED';
export const GET_LIFETAG_PROFILE_PUBLIC_CLEAR =
  'GET_LIFETAG_PROFILE_PUBLIC_CLEAR';

// LIFETAG LINK
export const SET_LINK_LIFETAG = 'SET_LINK_LIFETAG';
export const SET_LINK_LIFETAG_SUCCESS = 'SET_LINK_LIFETAG_SUCCESS';
export const SET_LINK_LIFETAG_FAILED = 'SET_LINK_LIFETAG_FAILED';
export const SET_LINK_LIFETAG_CLEAR = 'SET_LINK_LIFETAG_CLEAR';

// LIFETAG CREATE ORDER
export const SET_LIFETAG_CREATE_ORDER = 'SET_LIFETAG_CREATE_ORDER';
export const SET_LIFETAG_CREATE_ORDER_SUCCESS =
  'SET_LIFETAG_CREATE_ORDER_SUCCESS';
export const SET_LIFETAG_CREATE_ORDER_FAILED =
  'SET_LIFETAG_CREATE_ORDER_FAILED';
export const SET_LIFETAG_CREATE_ORDER_CLEAR = 'SET_LIFETAG_CREATE_ORDER_CLEAR';

// LIFETAG CURRENT SETTING
export const GET_LIFETAG_CURRENT_SETTING = 'GET_LIFETAG_CURRENT_SETTING';
export const GET_LIFETAG_CURRENT_SETTING_SUCCESS =
  'GET_LIFETAG_CURRENT_SETTING_SUCCESS';
export const GET_LIFETAG_CURRENT_SETTING_FAILED =
  'GET_LIFETAG_CURRENT_SETTING_FAILED';
export const GET_LIFETAG_CURRENT_SETTING_CLEAR =
  'GET_LIFETAG_CURRENT_SETTING_CLEAR';

// LIFETAG CHANGE SETTING
export const SET_LIFETAG_SECTION_SETTING = 'SET_LIFETAG_SECTION_SETTING';
export const SET_LIFETAG_SECTION_SETTING_SUCCESS =
  'SET_LIFETAG_SECTION_SETTING_SUCCESS';
export const SET_LIFETAG_SECTION_SETTING_FAILED =
  'SET_LIFETAG_SECTION_SETTING_FAILED';
export const SET_LIFETAG_SECTION_SETTING_CLEAR =
  'SET_LIFETAG_SECTION_SETTING_CLEAR';

// LIFETAG LIST ORDER
export const GET_LIFETAG_LIST_ORDER = 'GET_LIFETAG_LIST_ORDER';
export const GET_LIFETAG_LIST_ORDER_SUCCESS = 'GET_LIFETAG_LIST_ORDER_SUCCESS';
export const GET_LIFETAG_LIST_ORDER_FAILED = 'GET_LIFETAG_LIST_ORDER_FAILED';
export const GET_LIFETAG_LIST_ORDER_CLEAR = 'GET_LIFETAG_LIST_ORDER_CLEAR';

// LIFETAG DETAIL ORDER
export const GET_LIFETAG_DETAIL_ORDER = 'GET_LIFETAG_DETAIL_ORDER';
export const GET_LIFETAG_DETAIL_ORDER_SUCCESS =
  'GET_LIFETAG_DETAIL_ORDER_SUCCESS';
export const GET_LIFETAG_DETAIL_ORDER_FAILED =
  'GET_LIFETAG_DETAIL_ORDER_FAILED';
export const GET_LIFETAG_DETAIL_ORDER_CLEAR = 'GET_LIFETAG_DETAIL_ORDER_CLEAR';

// LIFETAG FLAG
export const GET_LIFETAG_FLAG = 'GET_LIFETAG_FLAG';
export const GET_LIFETAG_FLAG_SUCCESS = 'GET_LIFETAG_FLAG_SUCCESS';
export const GET_LIFETAG_FLAG_FAILED = 'GET_LIFETAG_FLAG_FAILED';
export const GET_LIFETAG_FLAG_CLEAR = 'GET_LIFETAG_FLAG_CLEAR';

// PRODUCT LIFETAG
export const GET_LIFETAG_LINKED_LIST = 'GET_LIFETAG';
export const GET_LIFETAG_LINKED_LIST_SUCCESS = 'GET_LIFETAG_SUCCESS';
export const GET_LIFETAG_LINKED_LIST_FAILED = 'GET_LIFETAG_FAILED';
export const GET_LIFETAG_LINKED_LIST_CLEAR = 'GET_LIFETAG_CLEAR';

// LIFETAG UPDATE
export const SET_LIFETAG_UPDATE = 'SET_LIFETAG_UPDATE';
export const SET_LIFETAG_UPDATE_SUCCESS = 'SET_LIFETAG_UPDATE_SUCCESS';
export const SET_LIFETAG_UPDATE_FAILED = 'SET_LIFETAG_UPDATE_FAILED';
export const SET_LIFETAG_UPDATE_CLEAR = 'SET_LIFETAG_UPDATE_CLEAR';

// LIFETAG UNLINK
export const SET_LIFETAG_UNLINK = 'SET_LIFETAG_UNLINK';
export const SET_LIFETAG_UNLINK_SUCCESS = 'SET_LIFETAG_UNLINK_SUCCESS';
export const SET_LIFETAG_UNLINK_FAILED = 'SET_LIFETAG_UNLINK_FAILED';
export const SET_LIFETAG_UNLINK_CLEAR = 'SET_LIFETAG_UNLINK_CLEAR';

// LIFETAG BLOODTYPE
export const LIFETAG_BLOODTYPE = [
  'A',
  'A+',
  'A-',
  'B',
  'B+',
  'B-',
  'AB',
  'AB+',
  'AB-',
  'O',
  'O+',
  'O-',
];

// LIFETAG ORDER NO
export const SET_LIFETAG_ORDERNO = 'SET_LIFETAG_ORDERNO';
export const SET_LIFETAG_ORDERNO_SUCCESS = 'SET_LIFETAG_ORDERNO_SUCCESS';
export const SET_LIFETAG_ORDERNO_FAILED = 'SET_LIFETAG_ORDERNO_FAILED';
export const SET_LIFETAG_ORDERNO_CLEAR = 'SET_LIFETAG_ORDERNO_CLEAR';

// LIFETAG UPDATE ORDER
export const SET_LIFETAG_UPDATE_ORDER = 'SET_LIFETAG_UPDATE_ORDER';
export const SET_LIFETAG_UPDATE_ORDER_SUCCESS =
  'SET_LIFETAG_UPDATE_ORDER_SUCCESS';
export const SET_LIFETAG_UPDATE_ORDER_FAILED =
  'SET_LIFETAG_UPDATE_ORDER_FAILED';
export const SET_LIFETAG_UPDATE_ORDER_CLEAR = 'SET_LIFETAG_UPDATE_ORDER_CLEAR';

// LIFETAG OTHER INFO
export const GET_LIFETAG_LIST_OTHER_INFO = 'GET_LIFETAG_LIST_OTHER_INFO';
export const GET_LIFETAG_LIST_OTHER_INFO_SUCCESS =
  'GET_LIFETAG_LIST_OTHER_INFO_SUCCESS';
export const GET_LIFETAG_LIST_OTHER_INFO_FAILED =
  'GET_LIFETAG_LIST_OTHER_INFO_FAILED';
export const GET_LIFETAG_LIST_OTHER_INFO_CLEAR =
  'GET_LIFETAG_LIST_OTHER_INFO_CLEAR';

// VERIFY PIN
export const GET_LIFETAG_VERIFY_PIN = 'GET_LIFETAG_VERIFY_PIN';
export const GET_LIFETAG_VERIFY_PIN_SUCCESS = 'GET_LIFETAG_VERIFY_PIN_SUCCESS';
export const GET_LIFETAG_VERIFY_PIN_FAILED = 'GET_LIFETAG_VERIFY_PIN_FAILED';
export const GET_LIFETAG_VERIFY_PIN_CLEAR = 'GET_LIFETAG_VERIFY_PIN_CLEAR';

// OTP REQUEST
export const SET_LIFETAG_UNLINK_REQUEST_OTP = 'SET_LIFETAG_UNLINK_REQUEST_OTP';
export const SET_LIFETAG_UNLINK_REQUEST_OTP_SUCCESS =
  'SET_LIFETAG_UNLINK_REQUEST_OTP_SUCCESS';
export const SET_LIFETAG_UNLINK_REQUEST_OTP_FAILED =
  'SET_LIFETAG_UNLINK_REQUEST_OTP_FAILED';
export const SET_LIFETAG_UNLINK_REQUEST_OTP_CLEAR =
  'SET_LIFETAG_UNLINK_REQUEST_OTP_CLEAR';

// OTP VERIFY
export const SET_LIFETAG_UNLINK_VERIFY_OTP = 'SET_LIFETAG_UNLINK_VERIFY_OTP';
export const SET_LIFETAG_UNLINK_VERIFY_OTP_SUCCESS =
  'SET_LIFETAG_UNLINK_VERIFY_OTP_SUCCESS';
export const SET_LIFETAG_UNLINK_VERIFY_OTP_FAILED =
  'SET_LIFETAG_UNLINK_VERIFY_OTP_FAILED';
export const SET_LIFETAG_UNLINK_VERIFY_OTP_CLEAR =
  'SET_LIFETAG_UNLINK_VERIFY_OTP_CLEAR';

// CREATE PIN
export const SET_LIFETAG_CREATE_PIN = 'SET_LIFETAG_CREATE_PIN';
export const SET_LIFETAG_CREATE_PIN_SUCCESS = 'SET_LIFETAG_CREATE_PIN_SUCCESS';
export const SET_LIFETAG_CREATE_PIN_FAILED = 'SET_LIFETAG_CREATE_PIN_FAILED';
export const SET_LIFETAG_CREATE_PIN_CLEAR = 'SET_LIFETAG_CREATE_PIN_CLEAR';