export const GET_FAQ_CLAIM = 'GET_FAQ_CLAIM'
export const GET_FAQ_CLAIM_SUCCESS = 'GET_FAQ_CLAIM_SUCCESS'
export const GET_FAQ_CLAIM_FAILED = 'GET_FAQ_CLAIM_FAILED'
export const GET_FAQ_CLAIM_DETAIL = 'GET_FAQ_CLAIM_DETAIL'
export const GET_FAQ_CLAIM_DETAIL_SUCCESS = 'GET_FAQ_CLAIM_DETAIL_SUCCESS'
export const GET_FAQ_CLAIM_DETAIL_FAILED = 'GET_FAQ_CLAIM_DETAIL_FAILED'
export const GET_POLICY_DIGITAL = 'GET_POLICY_DIGITAL'
export const GET_POLICY_DIGITAL_CLEAR = 'GET_POLICY_DIGITAL_CLEAR'
export const GET_POLICY_DIGITAL_SUCCESS = 'GET_POLICY_DIGITAL_SUCCESS'
export const GET_POLICY_DIGITAL_FAILED = 'GET_POLICY_DIGITAL_FAILED'
export const SET_UPLOAD_DOC = 'SET_UPLOAD_DOC'
export const SET_UPLOAD_DOC_CLEAR = 'SET_UPLOAD_DOC_CLEAR'
export const GET_RS = 'GET_RS'
export const GET_RS_SUCCESS = 'GET_RS_SUCCESS'
export const GET_RS_FAILED = 'GET_RS_FAILED'
export const SET_POLICY = 'SET_POLICY'
export const GET_LIST_TYPE_BENEFIT = 'GET_LIST_TYPE_BENEFIT'
export const GET_LIST_TYPE_BENEFIT_SUCCESS = 'GET_LIST_TYPE_BENEFIT_SUCCESS'
export const GET_LIST_TYPE_BENEFIT_FAILED = 'GET_LIST_TYPE_BENEFIT_FAILED'
export const SET_DATA_CLAIM = 'SET_DATA_CLAIM'

/** Document Mandatory */
export const GET_DOCUMENT_MANDATORY = 'GET_DOCUMENT_MANDATORY';
export const GET_DOCUMENT_MANDATORY_SUCCESS = 'GET_DOCUMENT_MANDATORY_SUCCESS';
export const GET_DOCUMENT_MANDATORY_FAILED = 'GET_DOCUMENT_MANDATORY_FAILED';
export const GET_DOCUMENT_MANDATORY_CLEAR = 'GET_DOCUMENT_MANDATORY_CLEAR';

/** upload document */
export const SET_UPLOAD_DOCUMENT = 'SET_UPLOAD_DOCUMENT';
export const SET_UPLOAD_DOCUMENT_SUCCESS = 'SET_UPLOAD_DOCUMENT_SUCCESS';
export const SET_UPLOAD_DOCUMENT_FAILED = 'SET_UPLOAD_DOCUMENT_FAILED';
export const SET_UPLOAD_DOCUMENT_CLEAR = 'SET_UPLOAD_DOCUMENT_CLEAR';

/** submit document */
export const SET_SUBMIT_DOCUMENT = 'SET_SUBMIT_DOCUMENT';
export const SET_SUBMIT_DOCUMENT_SUCCESS = 'SET_SUBMIT_DOCUMENT_SUCCESS';
export const SET_SUBMIT_DOCUMENT_FAILED = 'SET_SUBMIT_DOCUMENT_FAILED';
export const SET_SUBMIT_DOCUMENT_CLEAR = 'SET_SUBMIT_DOCUMENT_CLEAR';

export const benefitTypeTranslation = (type) => {
    const translation = {
        ['DEATH_ACCIDENT']: 'Kecelakaan',
        DEFAULT: '',
    }
    return translation[type] || translation.DEFAULT
}
