export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';
export const GET_PRODUCT_CLEAR = 'GET_PRODUCT_CLEAR';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';
export const GET_PRODUCTS_CLEAR = 'GET_PRODUCTS_CLEAR';

export const GET_LIST_RS = 'GET_LIST_RS';
export const GET_LIST_RS_SUCCESS = 'GET_LIST_RS_SUCCESS';
export const GET_LIST_RS_FAILED = 'GET_LIST_RS_FAILED';
export const GET_LIST_RS_CLEAR = 'GET_LIST_RS_CLEAR';

export const GET_PERSONAL_RIPLAY = 'GET_PERSONAL_RIPLAY';
export const GET_PERSONAL_RIPLAY_SUCCESS = 'GET_PERSONAL_RIPLAY_SUCCESS';
export const GET_PERSONAL_RIPLAY_FAILED = 'GET_PERSONAL_RIPLAY_FAILED';
export const GET_PERSONAL_RIPLAY_CLEAR = 'GET_PERSONAL_RIPLAY_CLEAR';

export const SET_SUBMISSION = 'SET_SUBMISSION';
export const SET_SUBMISSION_SUCCESS = 'SET_SUBMISSION_SUCCESS';
export const SET_SUBMISSION_FAILED = 'SET_SUBMISSION_FAILED';
export const SET_SUBMISSION_CLEAR = 'SET_SUBMISSION_CLEAR';

export const GET_CURRENT_SUBS = 'GET_CURRENT_SUBS';
export const GET_CURRENT_SUBS_SUCCESS = 'GET_CURRENT_SUBS_SUCCESS';
export const GET_CURRENT_SUBS_FAILED = 'GET_CURRENT_SUBS_FAILED';
export const GET_CURRENT_SUBS_CLEAR = 'GET_CURRENT_SUBS_CLEAR';

export const GET_INVITATION_LIST_FRIEND = 'GET_INVITATION_LIST_FRIEND';
export const GET_INVITATION_LIST_FRIEND_SUCCESS =
  'GET_INVITATION_LIST_FRIEND_SUCCESS';
export const GET_INVITATION_LIST_FRIEND_FAILED =
  'GET_INVITATION_LIST_FRIEND_FAILED';
export const GET_INVITATION_LIST_FRIEND_CLEAR =
  'GET_INVITATION_LIST_FRIEND_CLEAR';

export const GET_IS_USER_ELIGIBLE_BAJO_RUN = 'GET_IS_USER_ELIGIBLE_BAJO_RUN';
export const GET_IS_USER_ELIGIBLE_BAJO_RUN_SUCCESS =
  'GET_IS_USER_ELIGIBLE_BAJO_RUN_SUCCESS';
export const GET_IS_USER_ELIGIBLE_BAJO_RUN_FAILED =
  'GET_IS_USER_ELIGIBLE_BAJO_RUN_FAILED';
export const GET_IS_USER_ELIGIBLE_BAJO_RUN_CLEAR =
  'GET_IS_USER_ELIGIBLE_BAJO_RUN_CLEAR';

export const GET_BAJO_RUN_STEP = 'GET_BAJO_RUN_STEP';

export const SET_WAITING = 'SET_WAITING';
export const SET_WAITING_SUCCESS = 'SET_WAITING_SUCCESS';
export const SET_WAITING_FAILED = 'SET_WAITING_FAILED';
export const SET_WAITING_CLEAR = 'SET_WAITING_CLEAR';

export const GET_BAJO_RUN_PRODUCT = 'GET_BAJO_RUN_PRODUCT';
export const GET_BAJO_RUN_PRODUCT_SUCCESS = 'GET_BAJO_RUN_PRODUCT_SUCCESS';
export const GET_BAJO_RUN_PRODUCT_FAILED = 'GET_BAJO_RUN_PRODUCT_FAILED';

export const GET_PENDING_INVITES = 'GET_PENDING_INVITES';
export const GET_PENDING_INVITES_SUCCESS = 'GET_PENDING_INVITES_SUCCESS';
export const GET_PENDING_INVITES_FAILED = 'GET_PENDING_INVITES_FAILED';
export const GET_PENDING_INVITES_CLEAR = 'GET_PENDING_INVITES_CLEAR';

export const GET_CAMPAIGN = 'GET_CAMPAIGN';
export const GET_CAMPAIGN_SUCCESS = 'GET_CAMPAIGN_SUCCESS';
export const GET_CAMPAIGN_FAILED = 'GET_CAMPAIGN_FAILED';
export const GET_CAMPAIGN_CLEAR = 'GET_CAMPAIGN_CLEAR';

export const GET_ELIGIBLE_SUBMISSION = 'GET_ELIGIBLE_SUBMISSION';
export const GET_ELIGIBLE_SUBMISSION_SUCCESS =
  'GET_ELIGIBLE_SUBMISSION_SUCCESS';
export const GET_ELIGIBLE_SUBMISSION_FAILED = 'GET_ELIGIBLE_SUBMISSION_FAILED';
export const GET_ELIGIBLE_SUBMISSION_CLEAR = 'GET_ELIGIBLE_SUBMISSION_CLEAR';

export const GET_CHECK_MAX_INVITE = 'GET_CHECK_MAX_INVITE';
export const GET_CHECK_MAX_INVITE_SUCCESS = 'GET_CHECK_MAX_INVITE_SUCCESS';
export const GET_CHECK_MAX_INVITE_FAILED = 'GET_CHECK_MAX_INVITE_FAILED';
export const GET_CHECK_MAX_INVITE_CLEAR = 'GET_CHECK_MAX_INVITE_CLEAR';

export const GET_ELIGIBLE_LITE = 'GET_ELIGIBLE_LITE';
export const GET_ELIGIBLE_LITE_SUCCESS = 'GET_ELIGIBLE_LITE_SUCCESS';
export const GET_ELIGIBLE_LITE_FAILED = 'GET_ELIGIBLE_LITE_FAILED';
export const GET_ELIGIBLE_LITE_CLEAR = 'GET_ELIGIBLE_LITE_CLEAR';

export const GET_PRODUCT_LIFETAG = 'GET_PRODUCT_LIFETAG';
export const GET_PRODUCT_LIFETAG_SUCCESS = 'GET_PRODUCT_LIFETAG_SUCCESS';
export const GET_PRODUCT_LIFETAG_FAILED = 'GET_PRODUCT_LIFETAG_FAILED';
export const GET_PRODUCT_LIFETAG_CLEAR = 'GET_PRODUCT_LIFETAG_CLEAR';

export const GET_ELIGIBLE_POS = 'GET_ELIGIBLE_POS';
export const GET_ELIGIBLE_POS_SUCCESS = 'GET_ELIGIBLE_POS_SUCCESS';
export const GET_ELIGIBLE_POS_FAILED = 'GET_ELIGIBLE_POS_FAILED';
export const GET_ELIGIBLE_POS_CLEAR = 'GET_ELIGIBLE_POS_CLEAR';

export const GET_TOTAL_CLAIM = 'GET_TOTAL_CLAIM';
export const GET_TOTAL_CLAIM_SUCCESS = 'GET_TOTAL_CLAIM_SUCCESS';
export const GET_TOTAL_CLAIM_FAILED = 'GET_TOTAL_CLAIM_FAILED';
export const GET_TOTAL_CLAIM_CLEAR = 'GET_TOTAL_CLAIM_CLEAR';

export const SET_SUBMISSION_FOR_OTHER = 'SET_SUBMISSION_FOR_OTHER';
export const SET_SUBMISSION_FOR_OTHER_SUCCESS =
  'SET_SUBMISSION_FOR_OTHER_SUCCESS';
export const SET_SUBMISSION_FOR_OTHER_FAILED =
  'SET_SUBMISSION_FOR_OTHER_FAILED';
export const SET_SUBMISSION_FOR_OTHER_CLEAR = 'SET_SUBMISSION_FOR_OTHER_CLEAR';
export const SET_SUBMISSION_OLD = 'SET_SUBMISSION_OLD';
export const SET_SUBMISSION_OLD_SUCCESS = 'SET_SUBMISSION_OLD_SUCCESS';
export const SET_SUBMISSION_OLD_FAILED = 'SET_SUBMISSION_OLD_FAILED';
export const SET_SUBMISSION_OLD_CLEAR = 'SET_SUBMISSION_OLD_CLEAR';

export const GET_ID_CARD_DATA_OCR = 'GET_ID_CARD_DATA_OCR';
export const GET_ID_CARD_DATA_OCR_CLEAR = 'GET_ID_CARD_DATA_OCR_CLEAR';
export const GET_ID_CARD_DATA_OCR_SUCCESS = 'GET_ID_CARD_DATA_OCR_SUCCESS';
export const GET_ID_CARD_DATA_OCR_FAILED = 'GET_ID_CARD_DATA_OCR_FAILED';
