export const SET_UPDATA_LIVENESS = 'SET_UPDATA_LIVENESS';
export const SET_UPDATA_LIVENESS_SUCCESS = 'SET_UPDATA_LIVENESS_SUCCESS';
export const SET_UPDATA_LIVENESS_FAILED = 'SET_UPDATA_LIVENESS_FAILED';
export const SET_UPDATA_LIVENESS_CLEAR = 'SET_UPDATA_LIVENESS_CLEAR';

export const SET_UPDATA_KTP = 'SET_UPDATA_KTP';
export const SET_UPDATA_KTP_SUCCESS = 'SET_UPDATA_KTP_SUCCESS';
export const SET_UPDATA_KTP_FAILED = 'SET_UPDATA_KTP_FAILED';
export const SET_UPDATA_KTP_CLEAR = 'SET_UPDATA_KTP_CLEAR';

export const SET_UPDATA_KK = 'SET_UPDATA_KK';
export const SET_UPDATA_KK_SUCCESS = 'SET_UPDATA_KK_SUCCESS';
export const SET_UPDATA_KK_FAILED = 'SET_UPDATA_KK_FAILED';
export const SET_UPDATA_KK_CLEAR = 'SET_UPDATA_KK_CLEAR';

export const GET_UPDATA_LAST_KTP_INFO = 'GET_UPDATA_LAST_KTP_INFO';
export const GET_UPDATA_LAST_KTP_INFO_SUCCESS =
  'GET_UPDATA_LAST_KTP_INFO_SUCCESS';
export const GET_UPDATA_LAST_KTP_INFO_FAILED =
  'GET_UPDATA_LAST_KTP_INFO_FAILED';
export const GET_UPDATA_LAST_KTP_INFO_CLEAR = 'GET_UPDATA_LAST_KTP_INFO_CLEAR';

export const GET_UPDATA_LAST_KK_INFO = 'GET_UPDATA_LAST_KK_INFO';
export const GET_UPDATA_LAST_KK_INFO_SUCCESS =
  'GET_UPDATA_LAST_KK_INFO_SUCCESS';
export const GET_UPDATA_LAST_KK_INFO_FAILED = 'GET_UPDATA_LAST_KK_INFO_FAILED';
export const GET_UPDATA_LAST_KK_INFO_CLEAR = 'GET_UPDATA_LAST_KK_INFO_CLEAR';

export const GET_UPDATA_LAST_OTHER_INFO = 'GET_UPDATA_LAST_OTHER_INFO';
export const GET_UPDATA_LAST_OTHER_INFO_SUCCESS =
  'GET_UPDATA_LAST_OTHER_INFO_SUCCESS';
export const GET_UPDATA_LAST_OTHER_INFO_FAILED =
  'GET_UPDATA_LAST_OTHER_INFO_FAILED';
export const GET_UPDATA_LAST_OTHER_INFO_CLEAR =
  'GET_UPDATA_LAST_OTHER_INFO_CLEAR';
export const SET_UPDATA_CHECK_KK_KTP = 'SET_UPDATA_CHECK_KK_KTP';
export const SET_UPDATA_CHECK_KK_KTP_SUCCESS =
  'SET_UPDATA_CHECK_KK_KTP_SUCCESS';
export const SET_UPDATA_CHECK_KK_KTP_FAILED = 'SET_UPDATA_CHECK_KK_KTP_FAILED';
export const SET_UPDATA_CHECK_KK_KTP_CLEAR = 'SET_UPDATA_CHECK_KK_KTP_CLEAR';

export const SET_UPDATA_VERIFY_PENGKINIAN = 'SET_UPDATA_VERIFY_PENGKINIAN';
export const SET_UPDATA_VERIFY_PENGKINIAN_SUCCESS =
  'SET_UPDATA_VERIFY_PENGKINIAN_SUCCESS';
export const SET_UPDATA_VERIFY_PENGKINIAN_FAILED =
  'SET_UPDATA_VERIFY_PENGKINIAN_FAILED';
export const SET_UPDATA_VERIFY_PENGKINIAN_CLEAR =
  'SET_UPDATA_VERIFY_PENGKINIAN_CLEAR';

export const GET_UPDATA_LIST_BANK = 'GET_UPDATA_LIST_BANK';
export const GET_UPDATA_LIST_BANK_SUCCESS = 'GET_UPDATA_LIST_BANK_SUCCESS';
export const GET_UPDATA_LIST_BANK_FAILED = 'GET_UPDATA_LIST_BANK_FAILED';
export const GET_UPDATA_LIST_BANK_CLEAR = 'GET_UPDATA_LIST_BANK_CLEAR';

export const SET_UPDATA_REQUEST_OTP = 'SET_UPDATA_REQUEST_OTP';
export const SET_UPDATA_REQUEST_OTP_SUCCESS = 'SET_UPDATA_REQUEST_OTP_SUCCESS';
export const SET_UPDATA_REQUEST_OTP_FAILED = 'SET_UPDATA_REQUEST_OTP_FAILED';
export const SET_UPDATA_REQUEST_OTP_CLEAR = 'SET_UPDATA_REQUEST_OTP_CLEAR';

export const SET_UPDATA_VERIFY_OTP = 'SET_UPDATA_VERIFY_OTP';
export const SET_UPDATA_VERIFY_OTP_SUCCESS = 'SET_UPDATA_VERIFY_OTP_SUCCESS';
export const SET_UPDATA_VERIFY_OTP_FAILED = 'SET_UPDATA_VERIFY_OTP_FAILED';
export const SET_UPDATA_VERIFY_OTP_CLEAR = 'SET_UPDATA_VERIFY_OTP_CLEAR';

export const GET_UPDATA_PROVINCE = 'GET_UPDATA_PROVINCE';
export const GET_UPDATA_PROVINCE_SUCCESS = 'GET_UPDATA_PROVINCE_SUCCESS';
export const GET_UPDATA_PROVINCE_FAILED = 'GET_UPDATA_PROVINCE_FAILED';
export const GET_UPDATA_PROVINCE_CLEAR = 'GET_UPDATA_PROVINCE_CLEAR';

export const GET_UPDATA_CITY = 'GET_UPDATA_CITY';
export const GET_UPDATA_CITY_SUCCESS = 'GET_UPDATA_CITY_SUCCESS';
export const GET_UPDATA_CITY_FAILED = 'GET_UPDATA_CITY_FAILED';
export const GET_UPDATA_CITY_CLEAR = 'GET_UPDATA_CITY_CLEAR';

export const GET_UPDATA_DISTRICT = 'GET_UPDATA_DISTRICT';
export const GET_UPDATA_DISTRICT_SUCCESS = 'GET_UPDATA_DISTRICT_SUCCESS';
export const GET_UPDATA_DISTRICT_FAILED = 'GET_UPDATA_DISTRICT_FAILED';
export const GET_UPDATA_DISTRICT_CLEAR = 'GET_UPDATA_DISTRICT_CLEAR';

export const GET_UPDATA_SUB_DISTRICT = 'GET_UPDATA_SUB_DISTRICT';
export const GET_UPDATA_SUB_DISTRICT_SUCCESS =
  'GET_UPDATA_SUB_DISTRICT_SUCCESS';
export const GET_UPDATA_SUB_DISTRICT_FAILED = 'GET_UPDATA_SUB_DISTRICT_FAILED';
export const GET_UPDATA_SUB_DISTRICT_CLEAR = 'GET_UPDATA_SUB_DISTRICT_CLEAR';

export const SET_UPDATA_ALTER_POLICIES = 'SET_UPDATA_ALTER_POLICIES';
export const SET_UPDATA_ALTER_POLICIES_SUCCESS =
  'SET_UPDATA_ALTER_POLICIES_SUCCESS';
export const SET_UPDATA_ALTER_POLICIES_FAILED =
  'SET_UPDATA_ALTER_POLICIES_FAILED';
export const SET_UPDATA_ALTER_POLICIES_CLEAR =
  'SET_UPDATA_ALTER_POLICIES_CLEAR';

export const SET_UPDATA_INQUIRY_BANK_ACCOUNT =
  'SET_UPDATA_INQUIRY_BANK_ACCOUNT';
export const SET_UPDATA_INQUIRY_BANK_ACCOUNT_SUCCESS =
  'SET_UPDATA_INQUIRY_BANK_ACCOUNT_SUCCESS';
export const SET_UPDATA_INQUIRY_BANK_ACCOUNT_FAILED =
  'SET_UPDATA_INQUIRY_BANK_ACCOUNT_FAILED';
export const SET_UPDATA_INQUIRY_BANK_ACCOUNT_CLEAR =
  'SET_UPDATA_INQUIRY_BANK_ACCOUNT_CLEAR';

export const GET_UPDATA_DETAIL_EKYC = 'GET_UPDATA_DETAIL_EKYC';
export const GET_UPDATA_DETAIL_EKYC_SUCCESS = 'GET_UPDATA_DETAIL_EKYC_SUCCESS';
export const GET_UPDATA_DETAIL_EKYC_FAILED = 'GET_UPDATA_DETAIL_EKYC_FAILED';
export const GET_UPDATA_DETAIL_EKYC_CLEAR = 'GET_UPDATA_DETAIL_EKYC_CLEAR';

export const SET_UPDATA_BANK_UPLOAD = 'SET_UPDATA_BANK_UPLOAD';
export const SET_UPDATA_BANK_UPLOAD_SUCCESS = 'SET_UPDATA_BANK_UPLOAD_SUCCESS';
export const SET_UPDATA_BANK_UPLOAD_FAILED = 'SET_UPDATA_BANK_UPLOAD_FAILED';
export const SET_UPDATA_BANK_UPLOAD_CLEAR = 'SET_UPDATA_BANK_UPLOAD_CLEAR';

export const SET_UPDATA_FACECOMPARE = 'SET_UPDATA_FACECOMPARE';
export const SET_UPDATA_FACECOMPARE_SUCCESS = 'SET_UPDATA_FACECOMPARE_SUCCESS';
export const SET_UPDATA_FACECOMPARE_FAILED = 'SET_UPDATA_FACECOMPARE_FAILED';
export const SET_UPDATA_FACECOMPARE_CLEAR = 'SET_UPDATA_FACECOMPARE_CLEAR';

export const GET_UPDATA_VALIDATION_CHECK = 'GET_UPDATA_VALIDATION_CHECK';
export const GET_UPDATA_VALIDATION_CHECK_SUCCESS =
  'GET_UPDATA_VALIDATION_CHECK_SUCCESS';
export const GET_UPDATA_VALIDATION_CHECK_FAILED =
  'GET_UPDATA_VALIDATION_CHECK_FAILED';
export const GET_UPDATA_VALIDATION_CHECK_CLEAR =
  'GET_UPDATA_VALIDATION_CHECK_CLEAR';
