export const SET_LANG = 'SET_LANG';
export const SET_COLOR_SCHEME = 'SET_COLOR_SCHEME';

export const SET_KYC_H5_LIVENESS_TOKEN = 'SET_KYC_H5_LIVENESS_TOKEN';
export const SET_KYC_H5_LIVENESS_TOKEN_SUCCESS = 'SET_KYC_H5_LIVENESS_TOKEN_SUCCESS';
export const SET_KYC_H5_LIVENESS_TOKEN_FAILED = 'SET_KYC_H5_LIVENESS_TOKEN_FAILED';
export const SET_KYC_H5_LIVENESS_TOKEN_CLEAR = 'SET_KYC_H5_LIVENESS_TOKEN_CLEAR';

export const SET_KYC_H5_LIVENESS_RESULT = 'SET_KYC_H5_LIVENESS_RESULT';
export const SET_KYC_H5_LIVENESS_RESULT_SUCCESS = 'SET_KYC_H5_LIVENESS_RESULT_SUCCESS';
export const SET_KYC_H5_LIVENESS_RESULT_FAILED = 'SET_KYC_H5_LIVENESS_RESULT_FAILED';
export const SET_KYC_H5_LIVENESS_RESULT_CLEAR = 'SET_KYC_H5_LIVENESS_RESULT_CLEAR';

export const SET_KYC_SELFIE = 'SET_KYC_SELFIE';
export const SET_KYC_SELFIE_SUCCESS = 'SET_KYC_SELFIE_SUCCESS';
export const SET_KYC_SELFIE_FAILED = 'SET_KYC_SELFIE_FAILED';
export const SET_KYC_SELFIE_CLEAR = 'SET_KYC_SELFIE_CLEAR';

export const SET_KYC_IDCARD = 'SET_KYC_IDCARD';
export const SET_KYC_IDCARD_SUCCESS = 'SET_KYC_IDCARD_SUCCESS';
export const SET_KYC_IDCARD_FAILED = 'SET_KYC_IDCARD_FAILED';
export const SET_KYC_IDCARD_CLEAR = 'SET_KYC_IDCARD_CLEAR';

export const SET_KYC_VERIFYIDCARD = 'SET_KYC_VERIFYIDCARD';
export const SET_KYC_VERIFYIDCARD_SUCCESS = 'SET_KYC_VERIFYIDCARD_SUCCESS';
export const SET_KYC_VERIFYIDCARD_FAILED = 'SET_KYC_VERIFYIDCARD_FAILED';
export const SET_KYC_VERIFYIDCARD_CLEAR = 'SET_KYC_VERIFYIDCARD_CLEAR';

export const SET_KYC_PIN = 'SET_KYC_PIN';
export const SET_KYC_PIN_SUCCESS = 'SET_KYC_PIN_SUCCESS';
export const SET_KYC_PIN_FAILED = 'SET_KYC_PIN_FAILED';
export const SET_KYC_PIN_CLEAR = 'SET_KYC_PIN_CLEAR';

export const SET_KYC_VERIFYDUKCAPIL = 'SET_KYC_VERIFYDUKCAPIL';
export const SET_KYC_VERIFYDUKCAPIL_SUCCESS = 'SET_KYC_VERIFYDUKCAPIL_SUCCESS';
export const SET_KYC_VERIFYDUKCAPIL_FAILED = 'SET_KYC_VERIFYDUKCAPIL_FAILED';
export const SET_KYC_VERIFYDUKCAPIL_CLEAR = 'SET_KYC_VERIFYDUKCAPIL_CLEAR';

export const SET_KYC_FACECOMPARE = 'SET_KYC_FACECOMPARE';
export const SET_KYC_FACECOMPARE_SUCCESS = 'SET_KYC_FACECOMPARE_SUCCESS';
export const SET_KYC_FACECOMPARE_FAILED = 'SET_KYC_FACECOMPARE_FAILED';
export const SET_KYC_FACECOMPARE_CLEAR = 'SET_KYC_FACECOMPARE_CLEAR';

export const SET_KYC_RATING = 'SET_KYC_RATING';
export const SET_KYC_RATING_SUCCESS = 'SET_KYC_RATING_SUCCESS';
export const SET_KYC_RATING_FAILED = 'SET_KYC_RATING_FAILED';
export const SET_KYC_RATING_CLEAR = 'SET_KYC_RATING_CLEAR';

export const SET_KYC_POSTALCODE_IDCARD = 'SET_KYC_POSTALCODE_IDCARD';
export const SET_KYC_POSTALCODE_IDCARD_SUCCESS =
  'SET_KYC_POSTALCODE_IDCARD_SUCCESS';
export const SET_KYC_POSTALCODE_IDCARD_FAILED =
  'SET_KYC_POSTALCODE_IDCARD_FAILED';
export const SET_KYC_POSTALCODE_IDCARD_CLEAR =
  'SET_KYC_POSTALCODE_IDCARD_CLEAR';

export const SET_KYC_REFACECOMPARE = 'SET_KYC_REFACECOMPARE';
export const SET_KYC_REFACECOMPARE_SUCCESS = 'SET_KYC_REFACECOMPARE_SUCCESS';
export const SET_KYC_REFACECOMPARE_FAILED = 'SET_KYC_REFACECOMPARE_FAILED';
export const SET_KYC_REFACECOMPARE_CLEAR = 'SET_KYC_REFACECOMPARE_CLEAR';
