export const GET_NOTIF = 'GET_NOTIF';
export const GET_NOTIF_SUCCESS = 'GET_NOTIF_SUCCESS';
export const GET_NOTIF_FAILED = 'GET_NOTIF_FAILED';
export const GET_NOTIF_CLEAR = 'GET_NOTIF_CLEAR';

export const GET_NOTIF_TRANSACTION = 'GET_NOTIF_TRANSACTION';
export const GET_NOTIF_TRANSACTION_SUCCESS = 'GET_NOTIF_TRANSACTION_SUCCESS';
export const GET_NOTIF_TRANSACTION_FAILED = 'GET_NOTIF_TRANSACTION_FAILED';
export const GET_NOTIF_TRANSACTION_CLEAR = 'GET_NOTIF_TRANSACTION_CLEAR';

export const READ_NOTIF = 'READ_NOTIF';
export const READ_NOTIF_SUCCESS = 'READ_NOTIF_SUCCESS';
export const READ_NOTIF_FAILED = 'READ_NOTIF_FAILED';
export const READ_NOTIF_CLEAR = 'READ_NOTIF_CLEAR';

// staus notifikasi transaksi
export const STATUS_ALL = 'semua';
export const STATUS_MENUNGGU_PEMBAYARAN = 'Menunggu Pembayaran';
export const STATUS_ON_PROCESS = 'ON_PROCESS';
export const STATUS_ON_DELIVERY = 'ON_DELIVERY';
export const STATUS_UNPAID = 'UNPAID';
