export const GET_POLICY = 'GET_POLICY';
export const GET_POLICY_SUCCESS = 'GET_POLICY_SUCCESS';
export const GET_POLICY_FAILED = 'GET_POLICY_FAILED';
export const GET_POLICY_CLEAR = 'GET_POLICY_CLEAR';

export const SET_LINK_POLICY = 'SET_LINK_POLICY';
export const SET_LINK_POLICY_SUCCESS = 'SET_LINK_POLICY_SUCCESS';
export const SET_LINK_POLICY_FAILED = 'SET_LINK_POLICY_FAILED';
export const SET_LINK_POLICY_CLEAR = 'SET_LINK_POLICY_CLEAR';

export const GET_POLICIES = 'GET_POLICIES';
export const GET_POLICIES_SUCCESS = 'GET_POLICIES_SUCCESS';
export const GET_POLICIES_FAILED = 'GET_POLICIES_FAILED';
export const GET_POLICIES_CLEAR = 'GET_POLICIES_CLEAR';

export const GET_CHECK_POLIS = 'GET_CHECK_POLIS';
export const GET_CHECK_POLIS_SUCCESS = 'GET_CHECK_POLIS_SUCCESS';
export const GET_CHECK_POLIS_FAILED = 'GET_CHECK_POLIS_FAILED';
export const GET_CHECK_POLIS_CLEAR = 'GET_CHECK_POLIS_CLEAR';

export const GET_NOTIF_COUNT = 'GET_NOTIF_COUNT';
export const GET_NOTIF_COUNT_SUCCESS = 'GET_NOTIF_COUNT_SUCCESS';
export const GET_NOTIF_COUNT_FAILED = 'GET_NOTIF_COUNT_FAILED';
export const GET_NOTIF_COUNT_CLEAR = 'GET_NOTIF_COUNT_CLEAR';

export const GET_WIDGET_MANFAAT = 'GET_WIDGET_MANFAAT';
export const GET_WIDGET_MANFAAT_SUCCESS = 'GET_WIDGET_MANFAAT_SUCCESS';
export const GET_WIDGET_MANFAAT_FAILED = 'GET_WIDGET_MANFAAT_FAILED';
export const GET_WIDGET_MANFAAT_CLEAR = 'GET_WIDGET_MANFAAT_CLEAR';

export const GET_PRODUCT_PRICES_FIT = 'GET_PRODUCT_PRICES_FIT';
export const GET_PRODUCT_PRICES_FIT_SUCCESS = 'GET_PRODUCT_PRICES_FIT_SUCCESS';
export const GET_PRODUCT_PRICES_FIT_FAILED = 'GET_PRODUCT_PRICES_FIT_FAILED';
export const GET_PRODUCT_PRICES_FIT_CLEAR = 'GET_PRODUCT_PRICES_FIT_CLEAR';

export const GET_PRODUCT_PRICES_FITPLUS = 'GET_PRODUCT_PRICES_FITPLUS';
export const GET_PRODUCT_PRICES_FITPLUS_SUCCESS =
  'GET_PRODUCT_PRICES_FITPLUS_SUCCESS';
export const GET_PRODUCT_PRICES_FITPLUS_FAILED =
  'GET_PRODUCT_PRICES_FITPLUS_FAILED';
export const GET_PRODUCT_PRICES_FITPLUS_CLEAR =
  'GET_PRODUCT_PRICES_FITPLUS_CLEAR';

export const GET_IS_USER_ELIGIBLE = 'GET_IS_USER_ELIGIBLE';
export const GET_IS_USER_ELIGIBLE_SUCCESS = 'GET_IS_USER_ELIGIBLE_SUCCESS';
export const GET_IS_USER_ELIGIBLE_FAILED = 'GET_IS_USER_ELIGIBLE_FAILED';
export const GET_IS_USER_ELIGIBLE_CLEAR = 'GET_IS_USER_ELIGIBLE_CLEAR';

export const GET_PRODUCT_BANNER = 'GET_PRODUCT_BANNER';
export const GET_PRODUCT_BANNER_SUCCESS = 'GET_PRODUCT_BANNER_SUCCESS';
export const GET_PRODUCT_BANNER_FAILED = 'GET_PRODUCT_BANNER_FAILED';
export const GET_PRODUCT_BANNER_CLEAR = 'GET_PRODUCT_BANNER_CLEAR';

export const GET_POLICY_WIDGET_HOME = 'GET_POLICY_WIDGET_HOME';
export const GET_POLICY_WIDGET_HOME_SUCCESS = 'GET_POLICY_WIDGET_HOME_SUCCESS';
export const GET_POLICY_WIDGET_HOME_FAILED = 'GET_POLICY_WIDGET_HOME_FAILED';
export const GET_POLICY_WIDGET_HOME_CLEAR = 'GET_POLICY_WIDGET_HOME_CLEAR';

export const GET_POLICY_WIDGET_HOME_PUBLIC = 'GET_POLICY_WIDGET_HOME_PUBLIC';
export const GET_POLICY_WIDGET_HOME_PUBLIC_SUCCESS =
  'GET_POLICY_WIDGET_HOME_PUBLIC_SUCCESS';
export const GET_POLICY_WIDGET_HOME_PUBLIC_FAILED =
  'GET_POLICY_WIDGET_HOME_PUBLIC_FAILED';
export const GET_POLICY_WIDGET_HOME_PUBLIC_CLEAR =
  'GET_POLICY_WIDGET_HOME_PUBLIC_CLEAR';

export const SET_CALL_TIME = 'SET_CALL_TIME';
export const SET_CALL_TIME_SUCCESS = 'SET_CALL_TIME_SUCCESS';
export const SET_CALL_TIME_FAILED = 'SET_CALL_TIME_FAILED';

export const GET_PENDING_INVITES = 'GET_PENDING_INVITES';
export const GET_PENDING_INVITES_SUCCESS = 'GET_PENDING_INVITES_SUCCESS';
export const GET_PENDING_INVITES_FAILED = 'GET_PENDING_INVITES_FAILED';
export const GET_PENDING_INVITES_CLEAR = 'GET_PENDING_INVITES_CLEAR';

export const GET_POLICY_PROPOSAL = 'GET_POLICY_PROPOSAL';
export const GET_POLICY_PROPOSAL_SUCCESS = 'GET_POLICY_PROPOSAL_SUCCESS';
export const GET_POLICY_PROPOSAL_FAILED = 'GET_POLICY_PROPOSAL_FAILED';
export const GET_POLICY_PROPOSAL_CLEAR = 'GET_POLICY_PROPOSAL_CLEAR';

export const SET_TEMPORARY_HOME_STATE = 'SET_TEMPORARY_HOME_STATE';

export const GET_WIDGET_IMAGE = 'GET_WIDGET_IMAGE';
export const GET_WIDGET_IMAGE_SUCCESS = 'GET_WIDGET_IMAGE_SUCCESS';
export const GET_WIDGET_IMAGE_FAILED = 'GET_WIDGET_IMAGE_FAILED';
export const GET_WIDGET_IMAGE_CLEAR = 'GET_WIDGET_IMAGE_CLEAR';

export const GET_FAQ_CONTENT = 'GET_FAQ_CONTENT';
export const GET_FAQ_CONTENT_SUCCESS = 'GET_FAQ_CONTENT_SUCCESS';
export const GET_FAQ_CONTENT_FAILED = 'GET_FAQ_CONTENT_FAILED';
export const GET_FAQ_CONTENT_CLEAR = 'GET_FAQ_CONTENT_CLEAR';

export const GET_IMPORTANT_FOR_YOU_IMAGE = 'GET_IMPORTANT_FOR_YOU_IMAGE';
export const GET_IMPORTANT_FOR_YOU_IMAGE_SUCCESS = 'GET_IMPORTANT_FOR_YOU_IMAGE_SUCCESS';
export const GET_IMPORTANT_FOR_YOU_IMAGE_FAILED = 'GET_IMPORTANT_FOR_YOU_IMAGE_FAILED';
export const GET_IMPORTANT_FOR_YOU_IMAGE_CLEAR = 'GET_IMPORTANT_FOR_YOU_IMAGE_CLEAR';
