export const SET_LANG = 'SET_LANG';
export const SET_COLOR_SCHEME = 'SET_COLOR_SCHEME';

// EVENT DETAIL
export const GET_EVENT_DETAIL = 'GET_EVENT_DETAIL';
export const GET_EVENT_DETAIL_SUCCESS = 'GET_EVENT_DETAIL_SUCCESS';
export const GET_EVENT_DETAIL_FAILED = 'GET_EVENT_DETAIL_FAILED';
export const GET_EVENT_DETAIL_CLEAR = 'GET_EVENT_DETAIL_CLEAR';
export const SET_EVENT_DETAIL = 'SET_EVENT_DETAIL';

// EVENT QUOTA (LEFTOVER TICKET)
export const GET_EVENT_QUOTA = 'GET_EVENT_QUOTA';
export const GET_EVENT_QUOTA_SUCCESS = 'GET_EVENT_QUOTA_SUCCESS';
export const GET_EVENT_QUOTA_FAILED = 'GET_EVENT_QUOTA_FAILED';
export const GET_EVENT_QUOTA_CLEAR = 'GET_EVENT_QUOTA_CLEAR';

// EVENT UPCOMMING
export const GET_EVENT_UPCOMING = 'GET_EVENT_UPCOMING';
export const GET_EVENT_UPCOMING_SUCCESS = 'GET_EVENT_UPCOMING_SUCCESS';
export const GET_EVENT_UPCOMING_FAILED = 'GET_EVENT_UPCOMING_FAILED';
export const GET_EVENT_UPCOMING_CLEAR = 'GET_EVENT_UPCOMING_CLEAR';
export const SET_EVENT_UPCOMING = 'SET_EVENT_UPCOMING';

// EVENT ADD FAV
export const SET_EVENT_ADDFAVORITE = 'SET_EVENT_ADDFAVORITE';
export const SET_EVENT_ADDFAVORITE_SUCCESS = 'SET_EVENT_ADDFAVORITE_SUCCESS';
export const SET_EVENT_ADDFAVORITE_FAILED = 'SET_EVENT_ADDFAVORITE_FAILED';
export const SET_EVENT_ADDFAVORITE_CLEAR = 'SET_EVENT_ADDFAVORITE_CLEAR';

// EVENT RM FAV
export const SET_EVENT_RMVFAVORITE = 'SET_EVENT_RMVFAVORITE';
export const SET_EVENT_RMVFAVORITE_SUCCESS = 'SET_EVENT_RMVFAVORITE_SUCCESS';
export const SET_EVENT_RMVFAVORITE_FAILED = 'SET_EVENT_RMVFAVORITE_FAILED';
export const SET_EVENT_RMVFAVORITE_CLEAR = 'SET_EVENT_RMVFAVORITE_CLEAR';

// EVENT FAV
export const GET_EVENT_FAVORITE = 'GET_EVENT_FAVORITE';
export const GET_EVENT_FAVORITE_SUCCESS = 'GET_EVENT_FAVORITE_SUCCESS';
export const GET_EVENT_FAVORITE_FAILED = 'GET_EVENT_FAVORITE_FAILED';
export const GET_EVENT_FAVORITE_CLEAR = 'GET_EVENT_FAVORITE_CLEAR';

// EVENT USERTICKET
export const GET_EVENT_USERTICKET = 'GET_EVENT_USERTICKET';
export const GET_EVENT_USERTICKET_SUCCESS = 'GET_EVENT_USERTICKET_SUCCESS';
export const GET_EVENT_USERTICKET_FAILED = 'GET_EVENT_USERTICKET_FAILED';
export const GET_EVENT_USERTICKET_CLEAR = 'GET_EVENT_USERTICKET_CLEAR';

// EVENT BUYTICKET
export const SET_EVENT_BUYTICKET = 'SET_EVENT_BUYTICKET';
export const SET_EVENT_BUYTICKET_SUCCESS = 'SET_EVENT_BUYTICKET_SUCCESS';
export const SET_EVENT_BUYTICKET_FAILED = 'SET_EVENT_BUYTICKET_FAILED';
export const SET_EVENT_BUYTICKET_CLEAR = 'SET_EVENT_BUYTICKET_CLEAR';

// EVENT ACCESSCODE
export const SET_EVENT_ACCESSCODE = 'SET_EVENT_ACCESSCODE';
export const SET_EVENT_ACCESSCODE_SUCCESS = 'SET_EVENT_ACCESSCODE_SUCCESS';
export const SET_EVENT_ACCESSCODE_FAILED = 'SET_EVENT_ACCESSCODE_FAILED';
export const SET_EVENT_ACCESSCODE_CLEAR = 'SET_EVENT_ACCESSCODE_CLEAR';

// EVENT CATEGORIES
export const GET_EVENT_CATEGORIES = 'GET_EVENT_CATEGORIES';
export const GET_EVENT_CATEGORIES_SUCCESS = 'GET_EVENT_CATEGORIES_SUCCESS';
export const GET_EVENT_CATEGORIES_FAILED = 'GET_EVENT_CATEGORIES_FAILED';
export const GET_EVENT_CATEGORIES_CLEAR = 'GET_EVENT_CATEGORIES_CLEAR';

// UTILITIES
export const SET_EVENT_PARAM = 'SET_EVENT_PARAM';
export const SET_MODAL_AKSES_KODE = 'SET_MODAL_AKSES_KODE';
export const SET_EVENT_FAVORITE = 'SET_EVENT_FAVORITE';

// GET USER EVENT INVOICE ID
export const GET_USER_EVENT_INVOICE_ID = 'GET_USER_EVENT_INVOICE_ID';
export const GET_USER_EVENT_INVOICE_ID_SUCCESS =
  'GET_USER_EVENT_INVOICE_ID_SUCCESS';
export const GET_USER_EVENT_INVOICE_ID_FAILED =
  'GET_USER_EVENT_INVOICE_ID_FAILED';
export const GET_USER_EVENT_INVOICE_ID_CLEAR =
  'GET_USER_EVENT_INVOICE_ID_CLEAR';

// CREATE BILL EVENT
export const SET_PAYMENT_EVENT = 'SET_PAYMENT_EVENT';
export const SET_PAYMENT_EVENT_SUCCESS = 'SET_PAYMENT_EVENT_SUCCESS';
export const SET_PAYMENT_EVENT_FAILED = 'SET_PAYMENT_EVENT_FAILED';
export const SET_PAYMENT_EVENT_CLEAR = 'SET_PAYMENT_EVENT_CLEAR';

// SET VALIDATE REFERRAL CODE
export const SET_VALIDATE_REFERRAL_CODE = 'SET_VALIDATE_REFERRAL_CODE';
export const SET_VALIDATE_REFERRAL_CODE_SUCCESS =
  'SET_VALIDATE_REFERRAL_CODE_SUCCESS';
export const SET_VALIDATE_REFERRAL_CODE_FAILED =
  'SET_VALIDATE_REFERRAL_CODE_FAILED';
export const SET_VALIDATE_REFERRAL_CODE_CLEAR =
  'SET_VALIDATE_REFERRAL_CODE_CLEAR';

// SET VALIDATE REFERRAL CODE
export const SET_VALIDATE_VOUCHER_CODE = 'SET_VALIDATE_VOUCHER_CODE';
export const SET_VALIDATE_VOUCHER_CODE_SUCCESS =
  'SET_VALIDATE_VOUCHER_CODE_SUCCESS';
export const SET_VALIDATE_VOUCHER_CODE_FAILED =
  'SET_VALIDATE_VOUCHER_CODE_FAILED';
export const SET_VALIDATE_VOUCHER_CODE_CLEAR =
  'SET_VALIDATE_VOUCHER_CODE_CLEAR';
