export const GET_PAYMENT_METHOD = 'GET_PAYMENT_METHOD';
export const GET_PAYMENT_METHOD_SUCCESS = 'GET_PAYMENT_METHOD_SUCCESS';
export const GET_PAYMENT_METHOD_FAILED = 'GET_PAYMENT_METHOD_FAILED';
export const GET_PAYMENT_METHOD_CLEAR = 'GET_PAYMENT_METHOD_CLEAR';

export const SET_CREATE_BILL = 'SET_CREATE_BILL';
export const SET_CREATE_BILL_SUCCESS = 'SET_CREATE_BILL_SUCCESS';
export const SET_CREATE_BILL_FAILED = 'SET_CREATE_BILL_FAILED';
export const SET_CREATE_BILL_CLEAR = 'SET_CREATE_BILL_CLEAR';

export const GET_PAYMENT_STATUS = 'GET_PAYMENT_STATUS';
export const GET_PAYMENT_STATUS_SUCCESS = 'GET_PAYMENT_STATUS_SUCCESS';
export const GET_PAYMENT_STATUS_FAILED = 'GET_PAYMENT_STATUS_FAILED';
export const GET_PAYMENT_STATUS_CLEAR = 'GET_PAYMENT_STATUS_CLEAR';

export const GET_PAYMENT_STATUS_V2 = 'GET_PAYMENT_STATUS_V2';
export const GET_PAYMENT_STATUS_V2_SUCCESS = 'GET_PAYMENT_STATUS_V2_SUCCESS';
export const GET_PAYMENT_STATUS_V2_FAILED = 'GET_PAYMENT_STATUS_V2_FAILED';
export const GET_PAYMENT_STATUS_V2_CLEAR = 'GET_PAYMENT_STATUS_V2_CLEAR';

export const GET_PAYMENT_HISTORY = 'GET_PAYMENT_HISTORY';

export const GET_CHECK_PAYMENT_PARAM = 'GET_CHECK_PAYMENT_PARAM';

export const ORDER_PAYMENT_METHOD = 'ORDER_PAYMENT_METHOD';
export const ORDER_PAYMENT_METHOD_SUCCESS = 'ORDER_PAYMENT_METHOD_SUCCESS';
export const ORDER_PAYMENT_METHOD_FAILED = 'ORDER_PAYMENT_METHOD_FAILED';
export const ORDER_PAYMENT_METHOD_CLEAR = 'ORDER_PAYMENT_METHOD_CLEAR';

export const DELETE_PAYMENT_METHOD = 'DELETE_PAYMENT_METHOD';
export const DELETE_PAYMENT_METHOD_SUCCESS = 'DELETE_PAYMENT_METHOD_SUCCESS';
export const DELETE_PAYMENT_METHOD_FAILED = 'DELETE_PAYMENT_METHOD_FAILED';
export const DELETE_PAYMENT_METHOD_CLEAR = 'DELETE_PAYMENT_METHOD_CLEAR';

export const GET_PAYMENT_EVENT_STATUS = 'GET_PAYMENT_EVENT_STATUS';
export const GET_PAYMENT_EVENT_STATUS_SUCCESS =
  'GET_PAYMENT_EVENT_STATUS_SUCCESS';
export const GET_PAYMENT_EVENT_STATUS_FAILED =
  'GET_PAYMENT_EVENT_STATUS_FAILED';
export const GET_PAYMENT_EVENT_STATUS_CLEAR = 'GET_PAYMENT_EVENT_STATUS_CLEAR';

export const GET_ADD_CARD_STATUS = 'GET_ADD_CARD_STATUS';
export const GET_ADD_CARD_STATUS_SUCCESS = 'GET_ADD_CARD_STATUS_SUCCESS';
export const GET_ADD_CARD_STATUS_FAILED = 'GET_ADD_CARD_STATUS_FAILED';
export const GET_ADD_CARD_STATUS_CLEAR = 'GET_ADD_CARD_STATUS_CLEAR';

// LIFETAG PAYMENT
export const SET_LIFETAG_PAYMENT_CHECK = 'SET_LIFETAG_PAYMENT_CHECK';
export const SET_LIFETAG_PAYMENT_CHECK_SUCCESS =
  'SET_LIFETAG_PAYMENT_CHECK_SUCCESS';
export const SET_LIFETAG_PAYMENT_CHECK_FAILED =
  'SET_LIFETAG_PAYMENT_CHECK_FAILED';
export const SET_LIFETAG_PAYMENT_CHECK_CLEAR =
  'SET_LIFETAG_PAYMENT_CHECK_CLEAR';
  
  export const GET_PAYMENT_STATUS_V3 = 'GET_PAYMENT_STATUS_V3';
  export const GET_PAYMENT_STATUS_V3_SUCCESS = 'GET_PAYMENT_STATUS_V3_SUCCESS';
  export const GET_PAYMENT_STATUS_V3_FAILED = 'GET_PAYMENT_STATUS_V3_FAILED';
  export const GET_PAYMENT_STATUS_V3_CLEAR = 'GET_PAYMENT_STATUS_V3_CLEAR';

  export const SET_CREATE_BILL_EVENT = 'SET_CREATE_BILL_EVENT';
  export const SET_CREATE_BILL_EVENT_SUCCESS = 'SET_CREATE_BILL_EVENT_SUCCESS';
  export const SET_CREATE_BILL_EVENT_FAILED = 'SET_CREATE_BILL_EVENT_FAILED';
  export const SET_CREATE_BILL_EVENT_CLEAR = 'SET_CREATE_BILL_EVENT_CLEAR';
