// LIFETAG INITIAL STATE
export const SET_LIFETAG_TEMP_STATE = 'SET_LIFETAG_TEMP_STATE';
export const SET_LIFETAG_TEMP_STATE_CLEAR = 'SET_LIFETAG_TEMP_STATE_CLEAR';
export const SET_LIFETAG_TEMP_ORDER_STATE = 'SET_LIFETAG_TEMP_ORDER_STATE';
export const SET_LIFETAG_TEMP_ORDER_STATE_CLEAR =
  'SET_LIFETAG_TEMP_ORDER_STATE_CLEAR';
export const SET_LIFETAG_OTHER_INFO = 'SET_LIFETAG_OTHER_INFO';

export const SET_IS_COMING_FROM_SCREEN = 'SET_IS_COMING_FROM_SCREEN';
export const SET_IS_COMING_FROM_DEEPLINK = 'SET_IS_COMING_FROM_DEEPLINK';

export const SET_LIVENESS_TEMP = 'SET_LIVENESS_TEMP';

// KKPM
export const SET_KKPM_TEMP = 'SET_KKPM_TEMP';
export const SET_KKPM_DATA_KK = 'SET_KKPM_DATA_KK';
export const SET_CLEAR_KKPM = 'SET_CLEAR_KKPM';
export const SET_IS_KTP_SAME = 'SET_IS_KTP_SAME';
export const SET_IS_KK_SAME = 'SET_IS_KK_SAME';
export const SET_UPDATA_OTHERINFORMATION = 'SET_UPDATA_OTHERINFORMATION';
export const SET_UPDATA_OTHERINFORMATION_CLEAR =
  'SET_UPDATA_OTHERINFORMATION_CLEAR';
export const SET_UPDATA_TEMP_STATE = 'SET_UPDATA_TEMP_STATE';
export const SET_UPDATA_TEMP_STATE_CLEAR = 'SET_UPDATA_TEMP_STATE_CLEAR';

// FORM BUY FOR OTHERS
export const SET_BUY_OTHERS_TEMP = 'SET_BUY_OTHERS_TEMP';
export const SET_CLEAR_BUY_OTHERS = 'SET_CLEAR_BUY_OTHERS';

//WIDGET HOMES
export const SET_WIDGET_HOME = 'SET_WIDGET_HOME';
