export const GET_USER_CONFIRMATION = 'GET_USER_CONFIRMATION';
export const GET_USER_CONFIRMATION_SUCCESS = 'GET_USER_CONFIRMATION_SUCCESS';
export const GET_USER_CONFIRMATION_FAILED = 'GET_USER_CONFIRMATION_FAILED';
