export const SET_SUBMISSION = 'LIFECOVER_SET_SUBMISSION';
export const SET_SUBMISSION_SUCCESS = 'LIFECOVER_SET_SUBMISSION_SUCCESS';
export const SET_SUBMISSION_FAILED = 'LIFECOVER_SET_SUBMISSION_FAILED';
