export const SET_REGISTER_OTP = 'SET_REGISTER_OTP';
export const SET_REGISTER_OTP_SUCCESS = 'SET_REGISTER_OTP_SUCCESS';
export const SET_REGISTER_OTP_FAILED = 'SET_REGISTER_OTP_FAILED';
export const SET_REGISTER_OTP_CLEAR = 'SET_REGISTER_OTP_CLEAR';

export const SET_REGISTER = 'SET_REGISTER';
export const SET_REGISTER_SUCCESS = 'SET_REGISTER_SUCCESS';
export const SET_REGISTER_FAILED = 'SET_REGISTER_FAILED';
export const SET_REGISTER_CLEAR = 'SET_REGISTER_CLEAR';

export const SET_REGISTER_SOCIAL = 'SET_REGISTER_SOCIAL';
export const SET_REGISTER_SOCIAL_SUCCESS = 'SET_REGISTER_SOCIAL_SUCCESS';
export const SET_REGISTER_SOCIAL_FAILED = 'SET_REGISTER_SOCIAL_FAILED';
export const SET_REGISTER_SOCIAL_CLEAR = 'SET_REGISTER_SOCIAL_CLEAR';

export const GET_INQUIRY_POLICY_NO = 'GET_INQUIRY_POLICY_NO';
export const GET_INQUIRY_POLICY_NO_SUCCESS = 'GET_INQUIRY_POLICY_NO_SUCCESS';
export const GET_INQUIRY_POLICY_NO_FAILED = 'GET_INQUIRY_POLICY_NO_FAILED';
export const GET_INQUIRY_POLICY_NO_CLEAR = 'GET_INQUIRY_POLICY_NO_CLEAR';

export const GET_CHECK_LINK_POLICY_NO = 'GET_CHECK_LINK_POLICY_NO';
export const GET_CHECK_LINK_POLICY_NO_SUCCESS =
  'GET_CHECK_LINK_POLICY_NO_SUCCESS';
export const GET_CHECK_LINK_POLICY_NO_FAILED =
  'GET_CHECK_LINK_POLICY_NO_FAILED';
export const GET_CHECK_LINK_POLICY_NO_CLEAR = 'GET_CHECK_LINK_POLICY_NO_CLEAR';
