export const GET_CURRENT_SUBS_LIFECOVER = 'GET_CURRENT_SUBS_LIFECOVER';
export const GET_CURRENT_SUBS_LIFECOVER_SUCCESS =
  'GET_CURRENT_SUBS_LIFECOVER_SUCCESS';
export const GET_CURRENT_SUBS_LIFECOVER_FAILED =
  'GET_CURRENT_SUBS_LIFECOVER_FAILED';
