export const SET_LOGIN = 'SET_LOGIN';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_FAILED = 'SET_LOGIN_FAILED';

export const SET_LOGOUT = 'SET_LOGOUT';
export const SET_LOGOUT_SUCCESS = 'SET_LOGOUT_SUCCESS';
export const SET_LOGOUT_FAILED = 'SET_LOGOUT_FAILED';

export const SET_LOGIN_CLEAR = 'SET_LOGIN_CLEAR';
export const SET_LOGIN_CLEAR_SUCCESS = 'SET_LOGIN_CLEAR_SUCCESS';
export const SET_LOGIN_CLEAR_FAILED = 'SET_LOGIN_CLEAR_FAILED';

export const SET_LOGIN_SOCIAL = 'SET_LOGIN_SOCIAL';
export const SET_LOGIN_SOCIAL_SUCCESS = 'SET_LOGIN_SOCIAL_SUCCESS';
export const SET_LOGIN_SOCIAL_FAILED = 'SET_LOGIN_SOCIAL_FAILED';
export const SET_LOGIN_SOCIAL_CLEAR = 'SET_LOGIN_SOCIAL_CLEAR';
