export const GET_RESET_PASS = 'GET_RESET_PASS';
export const GET_RESET_PASS_SUCCESS = 'GET_RESET_PASS_SUCCESS';
export const GET_RESET_PASS_FAILED = 'GET_RESET_PASS_FAILED';
export const GET_RESET_PASS_CLEAR = 'GET_RESET_PASS_CLEAR';

export const SET_RESET_PASS = 'SET_RESET_PASS';
export const SET_RESET_PASS_SUCCESS = 'SET_RESET_PASS_SUCCESS';
export const SET_RESET_PASS_FAILED = 'SET_RESET_PASS_FAILED';
export const SET_RESET_PASS_CLEAR = 'SET_RESET_PASS_CLEAR';
