export const CHECK_REFERRAL = 'CHECK_REFERRAL';
export const CHECK_REFERRAL_SUCCESS = 'CHECK_REFERRAL_SUCCESS';
export const CHECK_REFERRAL_FAILED = 'CHECK_REFERRAL_FAILED';
export const SET_REFERRAL = 'SET_REFERRAL';
