export const SET_LANG = 'SET_LANG';
export const SET_COLOR_SCHEME = 'SET_COLOR_SCHEME';

export const SET_PERSONAL_DATA = 'SET_PERSONAL_DATA';
export const SET_PERSONAL_DATA_SUCCESS = 'SET_PERSONAL_DATA_SUCCESS';
export const SET_PERSONAL_DATA_FAILED = 'SET_PERSONAL_DATA_FAILED';
export const SET_PERSONAL_DATA_CLEAR = 'SET_PERSONAL_DATA_CLEAR';

export const GET_PERSONAL_DATA = 'GET_PERSONAL_DATA';
export const GET_PERSONAL_DATA_SUCCESS = 'GET_PERSONAL_DATA_SUCCESS';
export const GET_PERSONAL_DATA_FAILED = 'GET_PERSONAL_DATA_FAILED';
export const GET_PERSONAL_DATA_CLEAR = 'GET_PERSONAL_DATA_CLEAR';

export const SET_USER_IDENTITY = 'SET_USER_IDENTITY';
export const SET_USER_IDENTITY_SUCCESS = 'SET_USER_IDENTITY_SUCCESS';
export const SET_USER_IDENTITY_FAILED = 'SET_USER_IDENTITY_FAILED';
export const SET_USER_IDENTITY_CLEAR = 'SET_USER_IDENTITY_CLEAR';

export const GET_USER_IDENTITY = 'GET_USER_IDENTITY';
export const GET_USER_IDENTITY_SUCCESS = 'GET_USER_IDENTITY_SUCCESS';
export const GET_USER_IDENTITY_FAILED = 'GET_USER_IDENTITY_FAILED';

export const SET_PROFILEDEVICE = 'SET_PROFILEDEVICE';
export const SET_PROFILEDEVICE_SUCCESS = 'SET_PROFILEDEVICE_SUCCESS';
export const SET_PROFILEDEVICE_FAILED = 'SET_PROFILEDEVICE_FAILED';
export const SET_PROFILEDEVICE_CLEAR = 'SET_PROFILEDEVICE_CLEAR';

export const GET_PROFILEDEVICE = 'GET_PROFILEDEVICE';
export const GET_PROFILEDEVICE_SUCCESS = 'GET_PROFILEDEVICE_SUCCESS';
export const GET_PROFILEDEVICE_FAILED = 'GET_PROFILEDEVICE_FAILED';
export const GET_PROFILEDEVICE_CLEAR = 'GET_PROFILEDEVICE_CLEAR';

export const SET_CREATE_PIN = 'SET_CREATE_PIN';
export const SET_CREATE_PIN_SUCCESS = 'SET_CREATE_PIN_SUCCESS';
export const SET_CREATE_PIN_FAILED = 'SET_CREATE_PIN_FAILED';
export const SET_CREATE_PIN_CLEAR = 'SET_CREATE_PIN_CLEAR';

export const SET_CHANGE_PIN = 'SET_CHANGE_PIN';
export const SET_CHANGE_PIN_SUCCESS = 'SET_CHANGE_PIN_SUCCESS';
export const SET_CHANGE_PIN_FAILED = 'SET_CHANGE_PIN_FAILED';
export const SET_CHANGE_PIN_CLEAR = 'SET_CHANGE_PIN_CLEAR';

export const GET_VERIFY_PIN = 'GET_VERIFY_PIN';
export const GET_VERIFY_PIN_SUCCESS = 'GET_VERIFY_PIN_SUCCESS';
export const GET_VERIFY_PIN_FAILED = 'GET_VERIFY_PIN_FAILED';
export const GET_VERIFY_PIN_CLEAR = 'GET_VERIFY_PIN_CLEAR';

export const SET_CHANGE_PASS = 'SET_CHANGE_PASS';
export const SET_CHANGE_PASS_SUCCESS = 'SET_CHANGE_PASS_SUCCESS';
export const SET_CHANGE_PASS_FAILED = 'SET_CHANGE_PASS_FAILED';
export const SET_CHANGE_PASS_CLEAR = 'SET_CHANGE_PASS_CLEAR';

export const SET_PHONE_NUMBER = 'SET_PHONE_NUMBER';
export const SET_PHONE_NUMBER_SUCCESS = 'SET_PHONE_NUMBER_SUCCESS';
export const SET_PHONE_NUMBER_FAILED = 'SET_PHONE_NUMBER_FAILED';
export const SET_PHONE_NUMBER_CLEAR = 'SET_PHONE_NUMBER_CLEAR';

export const SET_EMAIL = 'SET_EMAIL';
export const SET_EMAIL_SUCCESS = 'SET_EMAIL_SUCCESS';
export const SET_EMAIL_FAILED = 'SET_EMAIL_FAILED';
export const SET_EMAIL_CLEAR = 'SET_EMAIL_CLEAR';

export const SET_UPLOAD_PROFILE = 'SET_UPLOAD_PROFILE';
export const SET_UPLOAD_PROFILE_SUCCESS = 'SET_UPLOAD_PROFILE_SUCCESS';
export const SET_UPLOAD_PROFILE_FAILED = 'SET_UPLOAD_PROFILE_FAILED';
export const SET_UPLOAD_PROFILE_CLEAR = 'SET_UPLOAD_PROFILE_CLEAR';

export const SET_DELETE_FOTO_PROFILE = 'SET_DELETE_FOTO_PROFILE';
export const SET_DELETE_FOTO_PROFILE_SUCCESS =
  'SET_DELETE_FOTO_PROFILE_SUCCESS';
export const SET_DELETE_FOTO_PROFILE_FAILED = 'SET_DELETE_FOTO_PROFILE_FAILED';
export const SET_DELETE_FOTO_PROFILE_CLEAR = 'SET_DELETE_FOTO_PROFILE_CLEAR';

export const GET_CS_INFO = 'GET_CS_INFO';
export const GET_CS_INFO_SUCCESS = 'GET_CS_INFO_SUCCESS';
export const GET_CS_INFO_FAILED = 'GET_CS_INFO_FAILED';
export const GET_CS_INFO_CLEAR = 'GET_CS_INFO_CLEAR';

export const GET_PERSONAL_DATA_PROVINCE = 'GET_PERSONAL_DATA_PROVINCE';
export const GET_PERSONAL_DATA_PROVINCE_SUCCESS =
  'GET_PERSONAL_DATA_PROVINCE_SUCCESS';
export const GET_PERSONAL_DATA_PROVINCE_FAILED =
  'GET_PERSONAL_DATA_PROVINCE_FAILED';
export const GET_PERSONAL_DATA_PROVINCE_CLEAR =
  'GET_PERSONAL_DATA_PROVINCE_CLEAR';

export const SET_PERSONAL_DATA_PROVINCE = 'SET_PERSONAL_DATA_PROVINCE';
export const SET_PERSONAL_DATA_PROVINCE_CLEAR =
  'SET_PERSONAL_DATA_PROVINCE_CLEAR';

export const GET_PERSONAL_DATA_CITY = 'GET_PERSONAL_DATA_CITY';
export const GET_PERSONAL_DATA_CITY_SUCCESS = 'GET_PERSONAL_DATA_CITY_SUCCESS';
export const GET_PERSONAL_DATA_CITY_FAILED = 'GET_PERSONAL_DATA_CITY_FAILED';
export const GET_PERSONAL_DATA_CITY_CLEAR = 'GET_PERSONAL_DATA_CITY_CLEAR';

export const SET_PERSONAL_DATA_CITY = 'SET_PERSONAL_DATA_CITY';
export const SET_PERSONAL_DATA_CITY_CLEAR = 'SET_PERSONAL_DATA_CITY_CLEAR';

export const GET_PERSONAL_DATA_DISTRICT = 'GET_PERSONAL_DATA_DISTRICT';
export const GET_PERSONAL_DATA_DISTRICT_SUCCESS =
  'GET_PERSONAL_DATA_DISTRICT_SUCCESS';
export const GET_PERSONAL_DATA_DISTRICT_FAILED =
  'GET_PERSONAL_DATA_DISTRICT_FAILED';
export const GET_PERSONAL_DATA_DISTRICT_CLEAR =
  'GET_PERSONAL_DATA_DISTRICT_CLEAR';

export const SET_PERSONAL_DATA_DISTRICT = 'SET_PERSONAL_DATA_DISTRICT';
export const SET_PERSONAL_DATA_DISTRICT_CLEAR =
  'SET_PERSONAL_DATA_DISTRICT_CLEAR';

export const GET_PERSONAL_DATA_SUB_DISTRICT = 'GET_PERSONAL_DATA_SUB_DISTRICT';
export const GET_PERSONAL_DATA_SUB_DISTRICT_SUCCESS =
  'GET_PERSONAL_DATA_SUB_DISTRICT_SUCCESS';
export const GET_PERSONAL_DATA_SUB_DISTRICT_FAILED =
  'GET_PERSONAL_DATA_SUB_DISTRICT_FAILED';
export const GET_PERSONAL_DATA_SUB_DISTRICT_CLEAR =
  'GET_PERSONAL_DATA_SUB_DISTRICT_CLEAR';

export const SET_PROFILE_REQUEST_OTP = 'SET_PROFILE_REQUEST_OTP';
export const SET_PROFILE_REQUEST_OTP_SUCCESS =
  'SET_PROFILE_REQUEST_OTP_SUCCESS';
export const SET_PROFILE_REQUEST_OTP_FAILED = 'SET_PROFILE_REQUEST_OTP_FAILED';
export const SET_PROFILE_REQUEST_OTP_CLEAR = 'SET_PROFILE_REQUEST_OTP_CLEAR';

export const SET_PROFILE_VERIFY_OTP = 'SET_PROFILE_VERIFY_OTP';
export const SET_PROFILE_VERIFY_OTP_SUCCESS = 'SET_PROFILE_VERIFY_OTP_SUCCESS';
export const SET_PROFILE_VERIFY_OTP_FAILED = 'SET_PROFILE_VERIFY_OTP_FAILED';
export const SET_PROFILE_VERIFY_OTP_CLEAR = 'SET_PROFILE_VERIFY_OTP_CLEAR';

export const SET_PROFILE_FAQ = 'SET_PROFILE_FAQ';
export const SET_PROFILE_FAQ_SUCCESS = 'SET_PROFILE_FAQ_SUCCESS';
export const SET_PROFILE_FAQ_FAILED = 'SET_PROFILE_FAQ_FAILED';
export const SET_PROFILE_FAQ_CLEAR = 'SET_PROFILE_FAQ_CLEAR';

export const SET_PROFILE_NOLOGINFAQ = 'SET_PROFILE_NOLOGINFAQ';
export const SET_PROFILE_NOLOGINFAQ_SUCCESS = 'SET_PROFILE_NOLOGINFAQ_SUCCESS';
export const SET_PROFILE_NOLOGINFAQ_FAILED = 'SET_PROFILE_NOLOGINFAQ_FAILED';
export const SET_PROFILE_NOLOGINFAQ_CLEAR = 'SET_PROFILE_NOLOGINFAQ_CLEAR';

export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS';
export const GET_SUBSCRIPTIONS_SUCCESS = 'GET_SUBSCRIPTIONS_SUCCESS';
export const GET_SUBSCRIPTIONS_FAILED = 'GET_SUBSCRIPTIONS_FAILED';
export const GET_SUBSCRIPTIONS_CLEAR = 'GET_SUBSCRIPTIONS_CLEAR';

export const GET_SUBSCRIPTION_DETAIL = 'GET_SUBSCRIPTION_DETAIL';
export const GET_SUBSCRIPTION_DETAIL_SUCCESS =
  'GET_SUBSCRIPTION_DETAIL_SUCCESS';
export const GET_SUBSCRIPTION_DETAIL_FAILED = 'GET_SUBSCRIPTION_DETAIL_FAILED';
export const GET_SUBSCRIPTION_DETAIL_CLEAR = 'GET_SUBSCRIPTION_DETAIL_CLEAR';

export const SET_RESUBSCRIBE = 'SET_RESUBSCRIBE';
export const SET_RESUBSCRIBE_SUCCESS = 'SET_RESUBSCRIBE_SUCCESS';
export const SET_RESUBSCRIBE_FAILED = 'SET_RESUBSCRIBE_FAILED';
export const SET_RESUBSCRIBE_CLEAR = 'SET_RESUBSCRIBE_CLEAR';

export const SET_DELETE_ACCOUNT_REQUEST_OTP = 'SET_DELETE_ACCOUNT_REQUEST_OTP';
export const SET_DELETE_ACCOUNT_REQUEST_OTP_SUCCESS =
  'SET_DELETE_ACCOUNT_REQUEST_OTP_SUCCESS';
export const SET_DELETE_ACCOUNT_REQUEST_OTP_FAILED =
  'SET_DELETE_ACCOUNT_REQUEST_OTP_FAILED';
export const SET_DELETE_ACCOUNT_REQUEST_OTP_CLEAR =
  'SET_DELETE_ACCOUNT_REQUEST_OTP_CLEAR';

export const SET_DELETE_ACCOUNT_VERIFY_OTP = 'SET_DELETE_ACCOUNT_VERIFY_OTP';
export const SET_DELETE_ACCOUNT_VERIFY_OTP_SUCCESS =
  'SET_DELETE_ACCOUNT_VERIFY_OTP_SUCCESS';
export const SET_DELETE_ACCOUNT_VERIFY_OTP_FAILED =
  'SET_DELETE_ACCOUNT_VERIFY_OTP_FAILED';
export const SET_DELETE_ACCOUNT_VERIFY_OTP_CLEAR =
  'SET_DELETE_ACCOUNT_VERIFY_OTP_CLEAR';

export const GET_BILLS = 'GET_BILLS';
export const GET_BILLS_SUCCESS = 'GET_BILLS_SUCCESS';
export const GET_BILLS_FAILED = 'GET_BILLS_FAILED';
export const GET_BILLS_CLEAR = 'GET_BILLS_CLEAR';

export const GET_ADDRESS_LIST = 'GET_ADDRESS_LIST';
export const GET_ADDRESS_LIST_SUCCESS = 'GET_ADDRESS_LIST_SUCCESS';
export const GET_ADDRESS_LIST_FAILED = 'GET_ADDRESS_LIST_FAILED';
export const GET_ADDRESS_LIST_CLEAR = 'GET_ADDRESS_LIST_CLEAR';

export const SET_SAVE_ADDRESS = 'SET_SAVE_ADDRESS';
export const SET_SAVE_ADDRESS_SUCCESS = 'SET_SAVE_ADDRESS_SUCCESS';
export const SET_SAVE_ADDRESS_FAILED = 'SET_SAVE_ADDRESS_FAILED';
export const SET_SAVE_ADDRESS_CLEAR = 'SET_SAVE_ADDRESS_CLEAR';

export const SET_UPDATE_ADDRESS = 'SET_UPDATE_ADDRESS';
export const SET_UPDATE_ADDRESS_SUCCESS = 'SET_UPDATE_ADDRESS_SUCCESS';
export const SET_UPDATE_ADDRESS_FAILED = 'SET_UPDATE_ADDRESS_FAILED';
export const SET_UPDATE_ADDRESS_CLEAR = 'SET_UPDATE_ADDRESS_CLEAR';

export const SET_DELETE_ADDRESS = 'SET_DELETE_ADDRESS';
export const SET_DELETE_ADDRESS_SUCCESS = 'SET_DELETE_ADDRESS_SUCCESS';
export const SET_DELETE_ADDRESS_FAILED = 'SET_DELETE_ADDRESS_FAILED';
export const SET_DELETE_ADDRESS_CLEAR = 'SET_DELETE_ADDRESS_CLEAR';

export const GET_PROFILE_USER_PARTY = 'GET_PROFILE_USER_PARTY';
export const GET_PROFILE_USER_PARTY_SUCCESS = 'GET_PROFILE_USER_PARTY_SUCCESS';
export const GET_PROFILE_USER_PARTY_FAILED = 'GET_PROFILE_USER_PARTY_FAILED';
export const GET_PROFILE_USER_PARTY_CLEAR = 'GET_PROFILE_USER_PARTY_CLEAR';

export const GET_PROFILE_REFERRAL = 'GET_PROFILE_REFERRAL';
export const GET_PROFILE_REFERRAL_SUCCESS = 'GET_PROFILE_REFERRAL_SUCCESS';
export const GET_PROFILE_REFERRAL_FAILED = 'GET_PROFILE_REFERRAL_FAILED';
export const GET_PROFILE_REFERRAL_CLEAR = 'GET_PROFILE_REFERRAL_CLEAR';

export const GET_CONTACT = 'GET_CONTACT';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const GET_CONTACT_FAILED = 'GET_CONTACT_FAILED';
export const GET_CONTACT_CLEAR = 'GET_CONTACT_CLEAR';
