export const GET_LIST_REFERRAL = 'GET_LIST_REFERRAL';
export const GET_LIST_REFERRAL_SUCCESS = 'GET_LIST_REFERRAL_SUCCESS';
export const GET_LIST_REFERRAL_FAILED = 'GET_LIST_REFERRAL_FAILED';
export const GET_LIST_REFERRAL_CLEAR = 'GET_LIST_REFERRAL_CLEAR';
