export const GET_BENEFICIARY = 'GET_BENEFICIARY';
export const GET_BENEFICIARY_SUCCESS = 'GET_BENEFICIARY_SUCCESS';
export const GET_BENEFICIARY_FAILED = 'GET_BENEFICIARY_FAILED';
export const GET_BENEFICIARY_CLEAR = 'GET_BENEFICIARY_CLEAR';
