export const SET_LANG = 'SET_LANG';
export const SET_AUTH = 'SET_AUTH';
export const SET_DEVICE_ID = 'SET_DEVICE_ID';
export const SET_COLOR_SCHEME = 'SET_COLOR_SCHEME';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER_DATA = 'SET_USER_DATA';

export const SET_CLEAR_AUTH = 'SET_CLEAR_AUTH';
export const SET_CLEAR_AUTH_SUCCESS = 'SET_CLEAR_AUTH_SUCCESS';
export const SET_CLEAR_AUTH_FAILED = 'SET_CLEAR_AUTH_FAILED';

export const SET_LOGOUT = 'SET_LOGOUT';
export const SET_LOGOUT_SUCCESS = 'SET_LOGOUT_SUCCESS';
export const SET_LOGOUT_FAILED = 'SET_LOGOUT_FAILED';

export const SET_CLEAR_REFRESH_TOKEN = 'SET_CLEAR_REFRESH_TOKEN';

export const SET_DELETE_ACCOUNT = 'SET_DELETE_ACCOUNT';
export const SET_DELETE_ACCOUNT_SUCCESS = 'SET_DELETE_ACCOUNT_SUCCESS';
export const SET_DELETE_ACCOUNT_FAILED = 'SET_DELETE_ACCOUNT_FAILED';

export const GET_CHECK_ISSUED_POLICY = 'GET_CHECK_ISSUED_POLICY';
export const GET_CHECK_ISSUED_POLICY_SUCCESS =
  'GET_CHECK_ISSUED_POLICY_SUCCESS';
export const GET_CHECK_ISSUED_POLICY_FAILED = 'GET_CHECK_ISSUED_POLICY_FAILED';
export const SET_INVOICE_ID = 'SET_INVOICE_ID';
export const SET_PAYMENT_ID = 'SET_PAYMENT_ID';

export const SET_AUTH_VERIFY_PIN = 'SET_AUTH_VERIFY_PIN';
export const SET_AUTH_VERIFY_PIN_SUCCESS = 'SET_AUTH_VERIFY_PIN_SUCCESS';
export const SET_AUTH_VERIFY_PIN_FAILED = 'SET_AUTH_VERIFY_PIN_FAILED';
export const SET_AUTH_VERIFY_PIN_CLEAR = 'SET_AUTH_VERIFY_PIN_CLEAR';

export const SET_AUTH_REQUEST_OTP = 'SET_AUTH_REQUEST_OTP';
export const SET_AUTH_REQUEST_OTP_SUCCESS = 'SET_AUTH_REQUEST_OTP_SUCCESS';
export const SET_AUTH_REQUEST_OTP_FAILED = 'SET_AUTH_REQUEST_OTP_FAILED';
export const SET_AUTH_REQUEST_OTP_CLEAR = 'SET_AUTH_REQUEST_OTP_CLEAR';

export const SET_AUTH_CREATE_PIN = 'SET_AUTH_CREATE_PIN';
export const SET_AUTH_CREATE_PIN_SUCCESS = 'SET_AUTH_CREATE_PIN_SUCCESS';
export const SET_AUTH_CREATE_PIN_FAILED = 'SET_AUTH_CREATE_PIN_FAILED';
export const SET_AUTH_CREATE_PIN_CLEAR = 'SET_AUTH_CREATE_PIN_CLEAR';

export const SET_AUTH_VERIFY_OTP = 'SET_AUTH_VERIFY_OTP';
export const SET_AUTH_VERIFY_OTP_SUCCESS = 'SET_AUTH_VERIFY_OTP_SUCCESS';
export const SET_AUTH_VERIFY_OTP_FAILED = 'SET_AUTH_VERIFY_OTP_FAILED';
export const SET_AUTH_VERIFY_OTP_CLEAR = 'SET_AUTH_VERIFY_OTP_CLEAR';
