export const SET_ACTIVITY = 'SET_ACTIVITY';
export const SET_REQUEST_LOCATION_PERMISSION =
  'SET_REQUEST_LOCATION_PERMISSION';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_IS_SHOW_MODAL_COMING_SOON = 'SET_IS_SHOW_MODAL_COMING_SOON';
export const SET_UPLOAD_IMAGE_PROGRESS = 'SET_UPLOAD_IMAGE_PROGRESS';
export const SET_TOASTMSG = 'SET_TOASTMSG';
export const SET_ISPROGRESS_CODEPUSH = 'SET_ISPROGRESS_CODEPUSH';
export const SET_DIMENSIONS = 'SET_DIMENSIONS';
export const SET_IS_LOCATION_PERMISSION_GRANTED =
'SET_IS_LOCATION_PERMISSION_GRANTED';
export const SET_FIRST_LOAD = 'SET_FIRST_LOAD';
export const SET_APP_CONFIG = 'SET_APP_CONFIG';

// used
export const SET_INTERNAL_SERVER_ERROR = 'SET_INTERNAL_SERVER_ERROR';
export const SET_BETTER_OPEN_APP = 'SET_BETTER_OPEN_APP';
export const SET_CUSTOMER_CARE = 'SET_CUSTOMER_CARE';
export const SET_HOSPITAL = 'SET_HOSPITAL';
export const SET_FAQ_ASK = 'SET_FAQ_ASK';
export const SET_LOADING = 'SET_LOADING';
export const SET_NOT_AVAILABLE = 'SET_NOT_AVAILABLE';
export const SET_AVAILABLE_ON_MOBILE = 'SET_AVAILABLE_ON_MOBILE';
export const SET_IS_COMING_FROM_SCREEN = 'SET_IS_COMING_FROM_SCREEN';
export const SET_IS_COMING_FROM_DEEPLINK = 'SET_IS_COMING_FROM_DEEPLINK';
export const SET_EVENT_CODE = 'SET_EVENT_CODE';
export const SET_IS_ONLY_ADD_CARD = 'SET_IS_ONLY_ADD_CARD';
export const SET_IS_MODAL_TERM_N_CONDITION = 'SET_IS_MODAL_TERM_N_CONDITION';
export const SET_IS_MODAL_LS_TNC = 'SET_IS_MODAL_LS_TNC';
export const SET_IS_MODAL_SHOW_LS_RIPLAY = 'SET_IS_MODAL_SHOW_LS_RIPLAY';
export const SET_PAYLOAD_SUB_SUBSCRIBE = 'SET_PAYLOAD_SUB_SUBSCRIBE;'
export const SET_REFERRAL = 'SET_REFERRAL';

// modal lifetag
export const SET_LIFETAG_ACCESS_FAILED = 'SET_LIFETAG_ACCESS_FAILED';
export const SET_LIFETAG_NOT_ACTIVE = 'SET_LIFETAG_NOT_ACTIVE';
export const SET_LIFETAG_OUT_OFF_STOCK = 'SET_LIFETAG_OUT_OFF_STOCK';
export const SET_LIFETAG_PAIRING_FAILED = 'SET_LIFETAG_PAIRING_FAILED';
export const SET_LIFETAG_READY_TO_CONNECT = 'SET_LIFETAG_READY_TO_CONNECT';

export const SET_APPSFLYER_DATA = 'SET_APPSFLYER_DATA'
