export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS';
export const GET_SUBSCRIPTIONS_SUCCESS = 'GET_SUBSCRIPTIONS_SUCCESS';
export const GET_SUBSCRIPTIONS_FAILED = 'GET_SUBSCRIPTIONS_FAILED';
export const GET_SUBSCRIPTIONS_CLEAR = 'GET_SUBSCRIPTIONS_CLEAR';

export const GET_SUBSCRIPTION_DETAIL = 'GET_SUBSCRIPTION_DETAIL';
export const GET_SUBSCRIPTION_DETAIL_SUCCESS =
  'GET_SUBSCRIPTION_DETAIL_SUCCESS';
export const GET_SUBSCRIPTION_DETAIL_FAILED = 'GET_SUBSCRIPTION_DETAIL_FAILED';
export const GET_SUBSCRIPTION_DETAIL_CLEAR = 'GET_SUBSCRIPTION_DETAIL_CLEAR';

export const GET_BILLS = 'GET_BILLS';
export const GET_BILLS_SUCCESS = 'GET_BILLS_SUCCESS';
export const GET_BILLS_FAILED = 'GET_BILLS_FAILED';
export const GET_BILLS_CLEAR = 'GET_BILLS_CLEAR';

export const SET_RESUBSCRIBE = 'SET_RESUBSCRIBE';
export const SET_RESUBSCRIBE_SUCCESS = 'SET_RESUBSCRIBE_SUCCESS';
export const SET_RESUBSCRIBE_FAILED = 'SET_RESUBSCRIBE_FAILED';

export const SET_UNSUBSCRIBE = 'SET_UNSUBSCRIBE';
export const SET_UNSUBSCRIBE_SUCCESS = 'SET_UNSUBSCRIBE_SUCCESS';
export const SET_UNSUBSCRIBE_FAILED = 'SET_UNSUBSCRIBE_FAILED';

export const GET_SUBSCRIPTIONS_OTHER = 'GET_SUBSCRIPTIONS_OTHER';
export const GET_SUBSCRIPTIONS_OTHER_SUCCESS = 'GET_SUBSCRIPTIONS_OTHER_SUCCESS';
export const GET_SUBSCRIPTIONS_OTHER_FAILED = 'GET_SUBSCRIPTIONS_OTHER_FAILED';
export const GET_SUBSCRIPTIONS_OTHER_CLEAR = 'GET_SUBSCRIPTIONS_OTHER_CLEAR';
